"""1.2.5

Revision ID: 702b7666a634
Revises: ae61cfa6ada6
Create Date: 2023-04-14 13:08:44.689878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702b7666a634'
down_revision = 'ae61cfa6ada6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("DOWNLOAD_SETTING") as batch_op:
            batch_op.drop_column('CONTENT_LAYOUT')
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
