#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask ${UMASK}

if [ -f ${NASTOOL_CONFIG} ]; then
    NT_PORT=$(awk -F"[' ]+" '/web_port/{print $3}' /config/config.yaml)
else
    NT_PORT=3000
fi
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost ${NT_PORT}" \
    cd ${WORKDIR} s6-setuidgid nt python3 run.py