"""1.0.0

Revision ID: 6940fa00ebb9
Revises: 
Create Date: 2022-10-21 23:08:34.663081

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6940fa00ebb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("CUSTOM_WORDS") as batch_op:
        batch_op.alter_column('OFFSET', type_=sa.Text, existing_type=sa.Integer)
    op.execute('DROP TABLE IF EXISTS IGNORED_WORDS')
    op.execute('DROP TABLE IF EXISTS REPLACED_WORDS')
    op.execute('DROP TABLE IF EXISTS OFFSET_WORDS')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("CUSTOM_WORDS") as batch_op:
        batch_op.alter_column('OFFSET', type_=sa.Integer, existing_type=sa.Text)
    # ### end Alembic commands ###
