"""1.1.1

Revision ID: 1ee040543ac1
Revises: 720a6289a697
Create Date: 2023-02-21 08:18:12.861788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee040543ac1'
down_revision = '720a6289a697'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("DOWNLOAD_HISTORY") as batch_op:
            batch_op.add_column(sa.Column('DOWNLOADER', sa.Text))
            batch_op.add_column(sa.Column('DOWNLOAD_ID', sa.Text))
    except Exception as e:
        print(str(e))
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('LABEL', sa.Text))
    except Exception as e:
        print(str(e))
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.alter_column('DOWNLOAD_COUNT', type_=sa.Integer, existing_type=sa.Text)
            batch_op.alter_column('REMOVE_COUNT', type_=sa.Integer, existing_type=sa.Text)
            batch_op.alter_column('DOWNLOAD_SIZE', type_=sa.Integer, existing_type=sa.Text)
            batch_op.alter_column('UPLOAD_SIZE', type_=sa.Integer, existing_type=sa.Text)
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
