"""1.1.0

Revision ID: 371ef2cd23ee
Revises: cc7232dfe2b5
Create Date: 2023-01-13 15:30:20.994770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371ef2cd23ee'
down_revision = 'cc7232dfe2b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.add_column(sa.Column('OVER_EDITION', sa.Integer, nullable=True))
            batch_op.add_column(sa.Column('SITES', sa.Text, nullable=True))
            batch_op.add_column(sa.Column('FILTER_ARGS', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.drop_column('OVER_EDITION')
            batch_op.drop_column('SITES')
            batch_op.drop_column('FILTER_ARGS')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
