"""1.1.2

Revision ID: 4cccf1481cf7
Revises: 1ee040543ac1
Create Date: 2023-02-27 16:52:32.335739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cccf1481cf7'
down_revision = '1ee040543ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('LABEL', sa.Text))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('SITE_BRUSH_TASK', 'LABEL')
    # ### end Alembic commands ###
