"""1.0.1

Revision ID: 54a6d1df1565
Revises: 6940fa00ebb9
Create Date: 2022-11-05 22:56:42.673130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a6d1df1565'
down_revision = '6940fa00ebb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.add_column(sa.Column('SAVE_PATH', sa.Text))
            batch_op.add_column(sa.Column('DOWNLOAD_SETTING', sa.Integer))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
        batch_op.drop_column('SAVE_PATH')
        batch_op.drop_column('DOWNLOAD_SETTING')
    # ### end Alembic commands ###
