"""1.0.4

Revision ID: 57e5d4d9fad4
Revises: 850413b9cef1
Create Date: 2022-12-13 09:29:26.294215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e5d4d9fad4'
down_revision = '850413b9cef1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_USER_INFO_STATS") as batch_op:
            batch_op.add_column(sa.Column('FAVICON', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_USER_INFO_STATS") as batch_op:
            batch_op.drop_column('FAVICON')
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###
