"""1.0.11

Revision ID: 636549bd2eed
Revises: 94d22b44802d
Create Date: 2023-01-20 11:05:52.212836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636549bd2eed'
down_revision = '94d22b44802d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("RSS_MOVIES") as batch_op:
            batch_op.add_column(sa.Column('KEYWORD', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    try:
        with op.batch_alter_table("RSS_TVS") as batch_op:
            batch_op.add_column(sa.Column('KEYWORD', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("RSS_TVS") as batch_op:
            batch_op.drop_column('KEYWORD')
    except Exception as e:
        print(str(e))
    try:
        with op.batch_alter_table("RSS_MOVIES") as batch_op:
            batch_op.drop_column('KEYWORD')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
