"""1.1.2

Revision ID: 6fbd2e906728
Revises: 1ee040543ac1
Create Date: 2023-03-14 23:58:54.788181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fbd2e906728'
down_revision = '1ee040543ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("DOWNLOADER") as batch_op:
            batch_op.add_column(sa.Column('MATCH_PATH', sa.Integer))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###
    # alter table DOWNLOADER
    #     add MATCH_PATH INTEGER;



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
