"""1.0.3

Revision ID: 850413b9cef1
Revises: c2c9b1c8f84c
Create Date: 2022-11-14 02:28:36.135544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '850413b9cef1'
down_revision = 'c2c9b1c8f84c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("TRANSFER_HISTORY") as batch_op:
            batch_op.alter_column('FILE_PATH', new_column_name="SOURCE_PATH", existing_type=sa.Text)
            batch_op.alter_column('FILE_NAME', new_column_name="SOURCE_FILENAME", existing_type=sa.Text)
            batch_op.alter_column('SE', new_column_name="SEASON_EPISODE", existing_type=sa.Text)
            batch_op.add_column(sa.Column('TMDBID', sa.Integer))
            batch_op.add_column(sa.Column('DEST_PATH', sa.Text))
            batch_op.add_column(sa.Column('DEST_FILENAME', sa.Text))
    except Exception as e:
        print(str(e))
    try:
        with op.batch_alter_table("DOWNLOAD_SETTING") as batch_op:
            batch_op.add_column(sa.Column('DOWNLOADER', sa.Text))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("TRANSFER_HISTORY") as batch_op:
        batch_op.alter_column('SOURCE_PATH', new_column_name="FILE_PATH", existing_type=sa.Text)
        batch_op.alter_column('SOURCE_FILENAME', new_column_name="FILE_NAME", existing_type=sa.Text)
        batch_op.alter_column('SEASON_EPISODE', new_column_name="SE", existing_type=sa.Text)
        batch_op.drop_column('TMDBID')
        batch_op.drop_column('DEST_PATH')
        batch_op.drop_column('DEST_FILENAME')
    with op.batch_alter_table("DOWNLOAD_SETTING") as batch_op:
        batch_op.drop_column('DOWNLOADER')
    # ### end Alembic commands ###
