"""1.0.12

Revision ID: 90f5603816bd
Revises: 636549bd2eed
Create Date: 2023-01-20 19:44:47.439238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f5603816bd'
down_revision = '636549bd2eed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.add_column(sa.Column('OVER_EDITION', sa.Integer, nullable=True))
            batch_op.add_column(sa.Column('SITES', sa.Text, nullable=True))
            batch_op.add_column(sa.Column('FILTER_ARGS', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.drop_column('OVER_EDITION')
            batch_op.drop_column('SITES')
            batch_op.drop_column('FILTER_ARGS')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
