"""1.0.7

Revision ID: aba625bcc318
Revises: caa7e052da69
Create Date: 2023-01-06 05:32:48.599220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba625bcc318'
down_revision = 'caa7e052da69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("TRANSFER_UNKNOWN") as batch_op:
            batch_op.add_column(sa.Column('MODE', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("TRANSFER_UNKNOWN") as batch_op:
            batch_op.drop_column('MODE')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
