"""1.0.8

Revision ID: acbada719942
Revises: aba625bcc318
Create Date: 2023-01-07 14:52:33.371115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acbada719942'
down_revision = 'aba625bcc318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.add_column(sa.Column('RECOGNIZATION', sa.Text, nullable=True))
            batch_op.add_column(sa.Column('MEDIAINFOS', sa.Text, nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("CONFIG_USER_RSS") as batch_op:
            batch_op.drop_column('RECOGNIZATION')
            batch_op.drop_column('MEDIAINFOS')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
