"""1.0.2

Revision ID: c2c9b1c8f84c
Revises: 54a6d1df1565
Create Date: 2022-11-08 02:46:02.604678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c9b1c8f84c'
down_revision = '54a6d1df1565'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("RSS_MOVIES") as batch_op:
            batch_op.add_column(sa.Column('RSS_SITES', sa.Text))
            batch_op.add_column(sa.Column('SEARCH_SITES', sa.Text))
            batch_op.add_column(sa.Column('OVER_EDITION', sa.Integer))
            batch_op.add_column(sa.Column('FILTER_RESTYPE', sa.Text))
            batch_op.add_column(sa.Column('FILTER_PIX', sa.Text))
            batch_op.add_column(sa.Column('FILTER_RULE', sa.Integer))
            batch_op.add_column(sa.Column('FILTER_TEAM', sa.Text))
            batch_op.add_column(sa.Column('SAVE_PATH', sa.Text))
            batch_op.add_column(sa.Column('DOWNLOAD_SETTING', sa.Integer))
            batch_op.add_column(sa.Column('FUZZY_MATCH', sa.Integer))
            batch_op.add_column(sa.Column('NOTE', sa.Text))
    except Exception as e:
        print(str(e))
    try:
        with op.batch_alter_table("RSS_TVS") as batch_op:
            batch_op.add_column(sa.Column('RSS_SITES', sa.Text))
            batch_op.add_column(sa.Column('SEARCH_SITES', sa.Text))
            batch_op.add_column(sa.Column('OVER_EDITION', sa.Integer))
            batch_op.add_column(sa.Column('FILTER_RESTYPE', sa.Text))
            batch_op.add_column(sa.Column('FILTER_PIX', sa.Text))
            batch_op.add_column(sa.Column('FILTER_RULE', sa.Integer))
            batch_op.add_column(sa.Column('FILTER_TEAM', sa.Text))
            batch_op.add_column(sa.Column('SAVE_PATH', sa.Text))
            batch_op.add_column(sa.Column('DOWNLOAD_SETTING', sa.Integer))
            batch_op.add_column(sa.Column('FUZZY_MATCH', sa.Integer))
            batch_op.add_column(sa.Column('TOTAL_EP', sa.Integer))
            batch_op.add_column(sa.Column('CURRENT_EP', sa.Integer))
            batch_op.add_column(sa.Column('NOTE', sa.Text))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("RSS_MOVIES") as batch_op:
        batch_op.drop_column('RSS_SITES')
        batch_op.drop_column('SEARCH_SITES')
        batch_op.drop_column('OVER_EDITION')
        batch_op.drop_column('FILTER_RESTYPE')
        batch_op.drop_column('FILTER_PIX')
        batch_op.drop_column('FILTER_RULE')
        batch_op.drop_column('FILTER_TEAM')
        batch_op.drop_column('SAVE_PATH')
        batch_op.drop_column('DOWNLOAD_SETTING')
        batch_op.drop_column('FUZZY_MATCH')
        batch_op.drop_column('NOTE')
    with op.batch_alter_table("RSS_TVS") as batch_op:
        batch_op.drop_column('RSS_SITES')
        batch_op.drop_column('SEARCH_SITES')
        batch_op.drop_column('OVER_EDITION')
        batch_op.drop_column('FILTER_RESTYPE')
        batch_op.drop_column('FILTER_PIX')
        batch_op.drop_column('FILTER_RULE')
        batch_op.drop_column('FILTER_TEAM')
        batch_op.drop_column('SAVE_PATH')
        batch_op.drop_column('DOWNLOAD_SETTING')
        batch_op.drop_column('FUZZY_MATCH')
        batch_op.drop_column('TOTAL_EP')
        batch_op.drop_column('CURRENT_EP')
        batch_op.drop_column('NOTE')
    # ### end Alembic commands ###
