"""1.0.5

Revision ID: c58148a8c438
Revises: 57e5d4d9fad4
Create Date: 2022-12-20 09:29:10.421109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58148a8c438'
down_revision = '57e5d4d9fad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('DOUBAN_MEDIAS', sa.Column('ADD_TIME', sa.Text(), nullable=True))
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('DOUBAN_MEDIAS', 'ADD_TIME')
    except Exception as e:
        print(str(e))
    # ### end Alembic commands ###
