"""1.0.6

Revision ID: caa7e052da69
Revises: c58148a8c438
Create Date: 2023-01-02 02:03:56.528652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa7e052da69'
down_revision = 'c58148a8c438'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.add_column(sa.Column('SENDMESSAGE', sa.Text, nullable=True))
            batch_op.add_column(sa.Column('FORCEUPLOAD', sa.Text, nullable=True))
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("SITE_BRUSH_TASK") as batch_op:
            batch_op.drop_column('FORCEUPLOAD')
            batch_op.drop_column('SENDMESSAGE')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###
