"""3.0.2

Revision ID: ea6241f69d0c
Revises: 1ee040543ac1
Create Date: 2023-03-11 02:46:04.484806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6241f69d0c'
down_revision = '1ee040543ac1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SEARCH_RESULTS')
    op.drop_table('CONFIG_SEARCH_RULE')
    op.drop_table('SITE_BRUSH_DOWNLOADERS')
    op.drop_index('INDX_SITE_USER_STATISTICS_SITE', table_name='SITE_USER_STATISTICS')
    op.drop_index('INDX_SITE_USER_STATISTICS_URL', table_name='SITE_USER_STATISTICS')
    op.drop_index('UN_INDX_SITE_USER_STATISTICS_URL', table_name='SITE_USER_STATISTICS')
    op.drop_table('SITE_USER_STATISTICS')
    op.drop_index('INDX_MESSAGES_DATE', table_name='MESSAGES')
    op.drop_table('MESSAGES')
    op.drop_table('TEST_1')
    op.drop_table('SEARCH_TORRENTS_RESULT')
    op.drop_table('CONFIG_RSS_RULE')
    op.drop_index('INDX_SITE_STATISTICS_DS', table_name='SITE_STATISTICS')
    op.drop_table('SITE_STATISTICS')
    op.drop_index('INDX_CONFIG_USERS', table_name='CONFIG_USERS')
    op.create_index(op.f('ix_CONFIG_USERS_NAME'), 'CONFIG_USERS', ['NAME'], unique=False)
    op.drop_index('INDX_DOWNLOAD_HISTORY_DATE', table_name='DOWNLOAD_HISTORY')
    op.drop_index('INDX_DOWNLOAD_HISTORY_TITLE', table_name='DOWNLOAD_HISTORY')
    op.create_index(op.f('ix_DOWNLOAD_HISTORY_DATE'), 'DOWNLOAD_HISTORY', ['DATE'], unique=False)
    op.create_index(op.f('ix_DOWNLOAD_HISTORY_TITLE'), 'DOWNLOAD_HISTORY', ['TITLE'], unique=False)
    op.drop_index('INDX_RSS_MOVIES_NAME', table_name='RSS_MOVIES')
    op.create_index(op.f('ix_RSS_MOVIES_NAME'), 'RSS_MOVIES', ['NAME'], unique=False)
    op.drop_index('INDX_RSS_TORRENTS_URL', table_name='RSS_TORRENTS')
    op.create_index(op.f('ix_RSS_TORRENTS_ENCLOSURE'), 'RSS_TORRENTS', ['ENCLOSURE'], unique=False)
    op.drop_index('INDX_RSS_TVS_NAME', table_name='RSS_TVS')
    op.create_index(op.f('ix_RSS_TVS_NAME'), 'RSS_TVS', ['NAME'], unique=False)
    op.drop_index('INDX_RSS_TV_EPISODES_RSSID', table_name='RSS_TV_EPISODES')
    op.create_index(op.f('ix_RSS_TV_EPISODES_RSSID'), 'RSS_TV_EPISODES', ['RSSID'], unique=False)
    op.add_column('SITE_BRUSH_TASK', sa.Column('LABEL', sa.Text(), nullable=True))
    op.drop_column('SITE_BRUSH_TASK', 'FORCEUPLOAD')
    op.drop_index('INDX_SYNC_HISTORY', table_name='SYNC_HISTORY')
    op.create_index(op.f('ix_SYNC_HISTORY_PATH'), 'SYNC_HISTORY', ['PATH'], unique=False)
    op.drop_index('INDX_TRANSFER_BLACKLIST', table_name='TRANSFER_BLACKLIST')
    op.create_index(op.f('ix_TRANSFER_BLACKLIST_PATH'), 'TRANSFER_BLACKLIST', ['PATH'], unique=False)
    op.drop_index('INDX_TRANSFER_HISTORY_NAME', table_name='TRANSFER_HISTORY')
    op.drop_index('INDX_TRANSFER_HISTORY_PATH', table_name='TRANSFER_HISTORY')
    op.drop_index('INDX_TRANSFER_HISTORY_TITLE', table_name='TRANSFER_HISTORY')
    op.create_index(op.f('ix_TRANSFER_HISTORY_SOURCE_FILENAME'), 'TRANSFER_HISTORY', ['SOURCE_FILENAME'], unique=False)
    op.create_index(op.f('ix_TRANSFER_HISTORY_SOURCE_PATH'), 'TRANSFER_HISTORY', ['SOURCE_PATH'], unique=False)
    op.create_index(op.f('ix_TRANSFER_HISTORY_TITLE'), 'TRANSFER_HISTORY', ['TITLE'], unique=False)
    op.drop_index('INDX_TRANSFER_UNKNOWN', table_name='TRANSFER_UNKNOWN')
    op.drop_index('INDX_TRANSFER_UNKNOWN_STATE', table_name='TRANSFER_UNKNOWN')
    op.create_index(op.f('ix_TRANSFER_UNKNOWN_PATH'), 'TRANSFER_UNKNOWN', ['PATH'], unique=False)
    op.create_index(op.f('ix_TRANSFER_UNKNOWN_STATE'), 'TRANSFER_UNKNOWN', ['STATE'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TRANSFER_UNKNOWN_STATE'), table_name='TRANSFER_UNKNOWN')
    op.drop_index(op.f('ix_TRANSFER_UNKNOWN_PATH'), table_name='TRANSFER_UNKNOWN')
    op.create_index('INDX_TRANSFER_UNKNOWN_STATE', 'TRANSFER_UNKNOWN', ['STATE'], unique=False)
    op.create_index('INDX_TRANSFER_UNKNOWN', 'TRANSFER_UNKNOWN', ['PATH'], unique=False)
    op.drop_index(op.f('ix_TRANSFER_HISTORY_TITLE'), table_name='TRANSFER_HISTORY')
    op.drop_index(op.f('ix_TRANSFER_HISTORY_SOURCE_PATH'), table_name='TRANSFER_HISTORY')
    op.drop_index(op.f('ix_TRANSFER_HISTORY_SOURCE_FILENAME'), table_name='TRANSFER_HISTORY')
    op.create_index('INDX_TRANSFER_HISTORY_TITLE', 'TRANSFER_HISTORY', ['TITLE'], unique=False)
    op.create_index('INDX_TRANSFER_HISTORY_PATH', 'TRANSFER_HISTORY', ['SOURCE_PATH'], unique=False)
    op.create_index('INDX_TRANSFER_HISTORY_NAME', 'TRANSFER_HISTORY', ['SOURCE_FILENAME'], unique=False)
    op.drop_index(op.f('ix_TRANSFER_BLACKLIST_PATH'), table_name='TRANSFER_BLACKLIST')
    op.create_index('INDX_TRANSFER_BLACKLIST', 'TRANSFER_BLACKLIST', ['PATH'], unique=False)
    op.drop_index(op.f('ix_SYNC_HISTORY_PATH'), table_name='SYNC_HISTORY')
    op.create_index('INDX_SYNC_HISTORY', 'SYNC_HISTORY', ['PATH'], unique=False)
    op.add_column('SITE_BRUSH_TASK', sa.Column('FORCEUPLOAD', sa.TEXT(), nullable=True))
    op.drop_column('SITE_BRUSH_TASK', 'LABEL')
    op.drop_index(op.f('ix_RSS_TV_EPISODES_RSSID'), table_name='RSS_TV_EPISODES')
    op.create_index('INDX_RSS_TV_EPISODES_RSSID', 'RSS_TV_EPISODES', ['RSSID'], unique=False)
    op.drop_index(op.f('ix_RSS_TVS_NAME'), table_name='RSS_TVS')
    op.create_index('INDX_RSS_TVS_NAME', 'RSS_TVS', ['NAME'], unique=False)
    op.drop_index(op.f('ix_RSS_TORRENTS_ENCLOSURE'), table_name='RSS_TORRENTS')
    op.create_index('INDX_RSS_TORRENTS_URL', 'RSS_TORRENTS', ['ENCLOSURE'], unique=False)
    op.drop_index(op.f('ix_RSS_MOVIES_NAME'), table_name='RSS_MOVIES')
    op.create_index('INDX_RSS_MOVIES_NAME', 'RSS_MOVIES', ['NAME'], unique=False)
    op.drop_index(op.f('ix_DOWNLOAD_HISTORY_TITLE'), table_name='DOWNLOAD_HISTORY')
    op.drop_index(op.f('ix_DOWNLOAD_HISTORY_DATE'), table_name='DOWNLOAD_HISTORY')
    op.create_index('INDX_DOWNLOAD_HISTORY_TITLE', 'DOWNLOAD_HISTORY', ['TITLE'], unique=False)
    op.create_index('INDX_DOWNLOAD_HISTORY_DATE', 'DOWNLOAD_HISTORY', ['DATE'], unique=False)
    op.drop_index(op.f('ix_CONFIG_USERS_NAME'), table_name='CONFIG_USERS')
    op.create_index('INDX_CONFIG_USERS', 'CONFIG_USERS', ['NAME'], unique=False)
    op.create_table('SITE_STATISTICS',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('SITE', sa.TEXT(), nullable=True),
    sa.Column('DATE', sa.TEXT(), nullable=True),
    sa.Column('UPLOAD', sa.TEXT(), nullable=True),
    sa.Column('DOWNLOAD', sa.TEXT(), nullable=True),
    sa.Column('RATIO', sa.TEXT(), nullable=True),
    sa.Column('URL', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('INDX_SITE_STATISTICS_DS', 'SITE_STATISTICS', ['DATE', 'URL'], unique=False)
    op.create_table('CONFIG_RSS_RULE',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('NOTE', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('SEARCH_TORRENTS_RESULT',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('TORRENT_NAME', sa.TEXT(), nullable=True),
    sa.Column('ENCLOSURE', sa.TEXT(), nullable=True),
    sa.Column('DESCRIPTION', sa.TEXT(), nullable=True),
    sa.Column('TYPE', sa.TEXT(), nullable=True),
    sa.Column('TITLE', sa.TEXT(), nullable=True),
    sa.Column('YEAR', sa.TEXT(), nullable=True),
    sa.Column('SEASON', sa.TEXT(), nullable=True),
    sa.Column('EPISODE', sa.TEXT(), nullable=True),
    sa.Column('ES_STRING', sa.TEXT(), nullable=True),
    sa.Column('VOTE', sa.TEXT(), nullable=True),
    sa.Column('IMAGE', sa.TEXT(), nullable=True),
    sa.Column('POSTER', sa.TEXT(), nullable=True),
    sa.Column('TMDBID', sa.TEXT(), nullable=True),
    sa.Column('OVERVIEW', sa.TEXT(), nullable=True),
    sa.Column('RES_TYPE', sa.TEXT(), nullable=True),
    sa.Column('RES_ORDER', sa.TEXT(), nullable=True),
    sa.Column('SIZE', sa.INTEGER(), nullable=True),
    sa.Column('SEEDERS', sa.INTEGER(), nullable=True),
    sa.Column('PEERS', sa.INTEGER(), nullable=True),
    sa.Column('SITE', sa.TEXT(), nullable=True),
    sa.Column('SITE_ORDER', sa.TEXT(), nullable=True),
    sa.Column('FREELEECH', sa.TEXT(), nullable=True),
    sa.Column('PAGEURL', sa.TEXT(), nullable=True),
    sa.Column('OTHERINFO', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('TEST_1',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('UPLOAD', sa.TEXT(), nullable=True),
    sa.Column('DOWNLOAD', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('MESSAGES',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('LEVEL', sa.TEXT(), nullable=True),
    sa.Column('TITLE', sa.TEXT(), nullable=True),
    sa.Column('CONTENT', sa.TEXT(), nullable=True),
    sa.Column('DATE', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('INDX_MESSAGES_DATE', 'MESSAGES', ['DATE'], unique=False)
    op.create_table('SITE_USER_STATISTICS',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('SITE', sa.TEXT(), nullable=True),
    sa.Column('USERNAME', sa.TEXT(), nullable=True),
    sa.Column('USER_LEVEL', sa.TEXT(), nullable=True),
    sa.Column('JOIN_AT', sa.TEXT(), nullable=True),
    sa.Column('UPDATE_AT', sa.TEXT(), nullable=True),
    sa.Column('UPLOAD', sa.INTEGER(), nullable=True),
    sa.Column('DOWNLOAD', sa.INTEGER(), nullable=True),
    sa.Column('RATIO', sa.REAL(), nullable=True),
    sa.Column('SEEDING', sa.INTEGER(), nullable=True),
    sa.Column('LEECHING', sa.INTEGER(), nullable=True),
    sa.Column('SEEDING_SIZE', sa.INTEGER(), nullable=True),
    sa.Column('BONUS', sa.REAL(), nullable=True),
    sa.Column('URL', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index('UN_INDX_SITE_USER_STATISTICS_URL', 'SITE_USER_STATISTICS', ['URL'], unique=False)
    op.create_index('INDX_SITE_USER_STATISTICS_URL', 'SITE_USER_STATISTICS', ['URL'], unique=False)
    op.create_index('INDX_SITE_USER_STATISTICS_SITE', 'SITE_USER_STATISTICS', ['SITE'], unique=False)
    op.create_table('SITE_BRUSH_DOWNLOADERS',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('NAME', sa.TEXT(), nullable=True),
    sa.Column('TYPE', sa.TEXT(), nullable=True),
    sa.Column('HOST', sa.TEXT(), nullable=True),
    sa.Column('PORT', sa.TEXT(), nullable=True),
    sa.Column('USERNAME', sa.TEXT(), nullable=True),
    sa.Column('PASSWORD', sa.TEXT(), nullable=True),
    sa.Column('SAVE_DIR', sa.TEXT(), nullable=True),
    sa.Column('NOTE', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('CONFIG_SEARCH_RULE',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('INCLUDE', sa.TEXT(), nullable=True),
    sa.Column('EXCLUDE', sa.TEXT(), nullable=True),
    sa.Column('SIZE', sa.TEXT(), nullable=True),
    sa.Column('NOTE', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('SEARCH_RESULTS',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('TORRENT_NAME', sa.TEXT(), nullable=True),
    sa.Column('ENCLOSURE', sa.TEXT(), nullable=True),
    sa.Column('DESCRIPTION', sa.TEXT(), nullable=True),
    sa.Column('TYPE', sa.TEXT(), nullable=True),
    sa.Column('TITLE', sa.TEXT(), nullable=True),
    sa.Column('YEAR', sa.TEXT(), nullable=True),
    sa.Column('SEASON', sa.TEXT(), nullable=True),
    sa.Column('EPISODE', sa.TEXT(), nullable=True),
    sa.Column('ES_STRING', sa.TEXT(), nullable=True),
    sa.Column('VOTE', sa.TEXT(), nullable=True),
    sa.Column('IMAGE', sa.TEXT(), nullable=True),
    sa.Column('POSTER', sa.TEXT(), nullable=True),
    sa.Column('TMDBID', sa.TEXT(), nullable=True),
    sa.Column('OVERVIEW', sa.TEXT(), nullable=True),
    sa.Column('RES_TYPE', sa.TEXT(), nullable=True),
    sa.Column('RES_ORDER', sa.TEXT(), nullable=True),
    sa.Column('SIZE', sa.INTEGER(), nullable=True),
    sa.Column('SEEDERS', sa.INTEGER(), nullable=True),
    sa.Column('PEERS', sa.INTEGER(), nullable=True),
    sa.Column('SITE', sa.TEXT(), nullable=True),
    sa.Column('SITE_ORDER', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
