name: Build Nas-tools Base Image
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - requirements.txt
      - third_party.txt
      - docker/Dockerfile.base
      - .github/workflows/build-base-image.yml

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Base Image
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - 
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.base
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nas-tools-base-image:latest
